openapi: 3.0.3
servers:
  - url: https://127.0.0.1
    description: Local server.
info:
  version: 1.0.0
  title: Knot API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

paths:
  /api/chat/stream:
    post:
      tags:
        - Chat
      summary: Stream Chat
      description: Stream a chat conversation with an AI assistant using Server-Sent Events (SSE).
      operationId: streamChat
      parameters:
        - name: X-Knot-Api-Version
          in: header
          required: false
          schema:
            type: string
            default: "2025-03-10"
          description: API version
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Successful streaming response
          content:
            text/event-stream:
              schema:
                type: string
                description: Server-Sent Events stream containing chat responses
        '400':
          $ref: 'knot-openapi.yaml#/components/responses/bad-request'
        '401':
          $ref: 'knot-openapi.yaml#/components/responses/unauthorized'
        '503':
          description: Chat service not configured
          content:
            application/json:
              schema:
                $ref: 'knot-openapi.yaml#/components/schemas/error'
      security: [BearerAuth: []]

  /api/chat/completion:
    post:
      tags:
        - Chat
      summary: Chat Completion
      description: Get a complete chat completion response from an AI assistant in a single request (non-streaming).
      operationId: chatCompletion
      parameters:
        - name: X-Knot-Api-Version
          in: header
          required: false
          schema:
            type: string
            default: "2025-03-10"
          description: API version
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Successful completion response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatCompletionResponse'
        '400':
          $ref: 'knot-openapi.yaml#/components/responses/bad-request'
        '401':
          $ref: 'knot-openapi.yaml#/components/responses/unauthorized'
        '503':
          description: Chat service not configured
          content:
            application/json:
              schema:
                $ref: 'knot-openapi.yaml#/components/schemas/error'
      security: [BearerAuth: []]

  /api/chat/tools:
    get:
      tags:
        - Chat
      summary: List Available Tools
      description: Get a list of all available MCP tools and their parameters.
      operationId: listTools
      parameters:
        - name: X-Knot-Api-Version
          in: header
          required: false
          schema:
            type: string
            default: "2025-03-10"
          description: API version
      responses:
        '200':
          description: Successful response with tool list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tool'
        '401':
          $ref: 'knot-openapi.yaml#/components/responses/unauthorized'
        '500':
          description: MCP server not available
          content:
            application/json:
              schema:
                $ref: 'knot-openapi.yaml#/components/schemas/error'
      security: [BearerAuth: []]

  /api/chat/tools/call:
    post:
      tags:
        - Chat
      summary: Call Tool Directly
      description: Execute a tool directly without AI intervention.
      operationId: callTool
      parameters:
        - name: X-Knot-Api-Version
          in: header
          required: false
          schema:
            type: string
            default: "2025-03-10"
          description: API version
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ToolCallRequest'
      responses:
        '200':
          description: Successful tool execution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToolCallResponse'
        '400':
          $ref: 'knot-openapi.yaml#/components/responses/bad-request'
        '401':
          $ref: 'knot-openapi.yaml#/components/responses/unauthorized'
        '500':
          description: Tool execution failed
          content:
            application/json:
              schema:
                $ref: 'knot-openapi.yaml#/components/schemas/error'
      security: [BearerAuth: []]

components:
  schemas:
    ChatRequest:
      type: object
      properties:
        messages:
          type: array
          items:
            $ref: '#/components/schemas/ChatMessage'
          description: Array of chat messages
      required:
        - messages

    ChatMessage:
      type: object
      properties:
        role:
          type: string
          enum: [user, assistant, system, tool]
          description: The role of the message sender
        content:
          type: string
          description: The content of the message
        timestamp:
          type: integer
          format: int64
          description: Unix timestamp of the message
        tool_calls:
          type: array
          items:
            $ref: '#/components/schemas/ToolCall'
          description: Tool calls made in this message
        tool_call_id:
          type: string
          description: ID of the tool call this message responds to
      required:
        - role
        - content
        - timestamp

    ChatCompletionResponse:
      type: object
      properties:
        content:
          type: string
          description: The complete AI response content
      required:
        - content

    ToolCall:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the tool call
        type:
          type: string
          description: Type of the tool call
        function:
          $ref: '#/components/schemas/ToolCallFunction'
        index:
          type: integer
          description: Index of the tool call
      required:
        - id
        - type
        - function
        - index

    ToolCallFunction:
      type: object
      properties:
        name:
          type: string
          description: Name of the function to call
        arguments:
          type: object
          additionalProperties: true
          description: Arguments to pass to the function
      required:
        - name

    Tool:
      type: object
      properties:
        name:
          type: string
          description: The name of the tool
        description:
          type: string
          description: Description of what the tool does
        parameters:
          type: object
          additionalProperties: true
          description: JSON Schema describing the tool's parameters
      required:
        - name
        - description
        - parameters

    ToolCallRequest:
      type: object
      properties:
        name:
          type: string
          description: Name of the tool to call
        arguments:
          type: object
          additionalProperties: true
          description: Arguments to pass to the tool
      required:
        - name

    ToolCallResponse:
      type: object
      properties:
        content:
          description: The result content from the tool call
          oneOf:
            - type: string
            - type: object
            - type: array
            - type: number
            - type: boolean
      required:
        - content