openapi: 3.0.3
servers:
  - url: https://127.0.0.1
    description: Local server.

paths:
  /api/chat/stream:
    post:
      tags:
        - Chat
      summary: Stream Chat
      description: Stream a chat conversation with an AI assistant using Server-Sent Events (SSE).
      operationId: streamChat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Successful streaming response
          content:
            text/event-stream:
              schema:
                type: string
                description: Server-Sent Events stream containing chat responses
        '400':
          $ref: 'knot-openapi.yaml#/components/responses/bad-request'
        '401':
          $ref: 'knot-openapi.yaml#/components/responses/unauthorized'
        '503':
          description: Chat service not configured
          content:
            application/json:
              schema:
                $ref: 'knot-openapi.yaml#/components/schemas/error'
      security: [BearerAuth: []]

components:
  schemas:
    ChatRequest:
      type: object
      properties:
        messages:
          type: array
          items:
            $ref: '#/components/schemas/ChatMessage'
          description: Array of chat messages
      required:
        - messages

    ChatMessage:
      type: object
      properties:
        role:
          type: string
          enum: [user, assistant, system, tool]
          description: The role of the message sender
        content:
          type: string
          description: The content of the message
        timestamp:
          type: integer
          format: int64
          description: Unix timestamp of the message
        tool_calls:
          type: array
          items:
            $ref: '#/components/schemas/ToolCall'
          description: Tool calls made in this message
        tool_call_id:
          type: string
          description: ID of the tool call this message responds to
      required:
        - role
        - content
        - timestamp

    ToolCall:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the tool call
        type:
          type: string
          description: Type of the tool call
        function:
          $ref: '#/components/schemas/ToolCallFunction'
        index:
          type: integer
          description: Index of the tool call
      required:
        - id
        - type
        - function
        - index

    ToolCallFunction:
      type: object
      properties:
        name:
          type: string
          description: Name of the function to call
        arguments:
          type: object
          additionalProperties: true
          description: Arguments to pass to the function
      required:
        - name