openapi: 3.1.0
info:
  version: 1.0.0
  title: Knot API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    url: ../images/logo-light.svg
  description: >
    # Introduction

    The REST API is used for the CLI, Web interface and 3rd party integrations.

    See [Agent API](/api-docs/agent/) for the agent API.
tags:
  - name: Agents
    description: |
      Operations are for working with agents.
  - name: Authorization
    description: |
      This API is authenticated using a bearer token. The token is passed in the Authorization header as a Bearer token.

      A token can be obtained by logging in with the login endpoint and providing a valid username and password, or by creating a token with the create token endpoint.
  - name: API Tokens
    description: |
      Operations for working with API tokens.
  - name: Core
    description: |
      Core API endpoints.
  - name: Proxy
    description: |
      Endpoints for providing proxy services.
  - name: Spaces
    description: |
      Endpoints for working with spaces.
  - name: Users
    description: |
      These operations are for working with users.

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
    AgentAuth:
      type: http
      scheme: bearer

paths:
  /api/v1/users:
    $ref: paths/users.yaml
  /api/v1/users/{user_id}:
    $ref: paths/users_{user_id}.yaml
  /api/v1/users/whoami:
    $ref: paths/users_whoami.yaml

  /api/v1/groups:
    $ref: paths/groups.yaml
  /api/v1/groups/{group_id}:
    $ref: paths/groups_{group_id}.yaml

  /api/v1/roles:
    $ref: paths/roles.yaml

  /api/v1/sessions:
    $ref: paths/sessions.yaml
  /api/v1/sessions/{session_id}:
    $ref: paths/sessions_{session_id}.yaml

  /api/v1/auth:
    $ref: paths/auth.yaml
  /api/v1/auth/web:
    $ref: paths/auth_web.yaml
  /api/v1/auth/logout:
    $ref: paths/auth_logout.yaml

  /api/v1/tokens:
    $ref: paths/tokens.yaml
  /api/v1/tokens/{token_id}:
    $ref: paths/tokens_{token_id}.yaml

  /api/v1/spaces:
    $ref: paths/spaces.yaml
  /api/v1/spaces/{space_id}:
    $ref: paths/spaces_{space_id}.yaml
  /api/v1/spaces/{space_id}/service-state:
    $ref: paths/spaces_{space_id}_service-state.yaml
  /api/v1/spaces/{space_id}/start:
    $ref: paths/spaces_{space_id}_start.yaml
  /api/v1/spaces/{space_id}/stop:
    $ref: paths/spaces_{space_id}_stop.yaml
  /api/v1/spaces/stop-for-user/{user_id}:
    $ref: paths/spaces_stop-for-user_{user_id}.yaml

  /api/v1/templates:
    $ref: paths/templates.yaml
  /api/v1/templates/{template_id}:
    $ref: paths/templates_{template_id}.yaml

  /api/v1/templatevars:
    $ref: paths/templatevars.yaml
  /api/v1/templatevars/{templatvar_id}:
    $ref: paths/templatevars_{templatevar_id}.yaml

  /api/v1/volumes:
    $ref: paths/volumes.yaml
  /api/v1/volumes/{volume_id}:
    $ref: paths/volumes_{volume_id}.yaml
  /api/v1/volumes/{volume_id}/start:
    $ref: paths/volumes_{volume_id}_start.yaml
  /api/v1/volumes/{volume_id}/stop:
    $ref: paths/volumes_{volume_id}_stop.yaml

  /proxy/port/{host}/{port}:
    $ref: paths/proxy_port_{host}_{port}.yaml

  /api/v1/lookup/{service}:
    $ref: paths/lookup.yaml

  /api/v1/ping:
    $ref: paths/ping.yaml

  /api/v1/agents/{space_id}:
    $ref: paths/agents_{space_id}.yaml
  /api/v1/agents/{space_id}/status:
    $ref: paths/agents_{space_id}_status.yaml

  /api/v1/remote/servers:
    $ref: paths/remote-servers.yaml
  /api/v1/remote/remote/{server_id}:
    $ref: paths/remote-servers_{server_id}.yaml
